name: Build & Deploy Talks Page

on:
  push:
    branches: [main]  # or "master", depending on your default branch
  workflow_dispatch:  # allows manual triggering

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Generate HTML
        run: |
          pwd
          ./all.sh

      - name: Commit and push generated HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "maeddes@gmail.com"
          git add .
          git commit -m "Update generated index.html" || echo "No changes to commit"
          git push

     